kind: ConfigMap
apiVersion: v1
metadata:
  name: example-configmap
  labels:
    "kyma-watchable": "true"
    "operator.kyma-project.io/controller-name": "kyma"
data:
  database: mongodb
  database_uri: mongodb://localhost:27017
